permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:

# If new code is pushed to a PR branch, then cancel in progress workflows for
# that PR. Ensures that we don't waste CI time, and returns results quicker.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Build and Test
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.303

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build /WarnAsError --no-restore

      - name: Run tests
        run: dotnet test --no-build --no-restore

      # TODO: Get coverage
